"""user phone number added

Revision ID: 85a75eb38153
Revises: b173c286a336
Create Date: 2022-01-07 23:30:53.545551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85a75eb38153'
down_revision = 'b173c286a336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
